name: refilin_mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.4
  image_picker: ^0.8.6
  sp_util: 2.0.3
  material_design_icons_flutter: 6.0.7096
  location: 4.4.0
  geolocator: 9.0.2
  intl: ^0.18.0
  loading_animation_widget: ^1.2.0+4
  shimmer: ^3.0.0
  flutter_slidable: ^3.0.0
  dotted_border: ^2.0.0+3
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  google_fonts: ^4.0.4
  curved_navigation_bar: ^1.0.3
  geocoding: ^2.1.0
  carousel_slider: ^4.2.1
  json_annotation: ^4.8.1
  flutter_animate: 4.2.0
  flutter_rating_bar: ^4.0.1
  expandable_text: 2.3.0
  flutter:
    sdk: flutter
  collection: ^1.16.0
  google_maps_flutter: ^2.3.1
  sqflite: ^2.2.8+4
  clipboard: ^0.1.3
  animated_bottom_navigation_bar: ^1.2.0
  flutter_svg: ^2.0.7

dependency_overrides:
  image: ^3.2.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.1
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
    - assets/carousel/
    - assets/content/
    # - assets/models/

flutter_launcher_icons:
  android: launcher_icon
  image_path: "assets/icons/logo.png"
  web:
    image_path: path/to/image.png
    generate: true
  windows:
    image_path: path/to/image.png
    generate: true
    icon_size: 48
  macos:
    image_path: path/to/image.png
    generate: true
  ios: true
  min_sdk_android: 21
